#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -s 1920x1200
setxkbmap gb
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config single_monocle	 false

bspc rule -a virt-manager state=floating
# bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a feh state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a VirtualBox Machine state=floating
